spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restful?serverTimezone=UTC
    username: root
    password: 1a2a3a4a
  messages:
    basename: messages

#  security:
#    user:
#      name: username
#      password: 1234

server:
  port: 8081

logging:
  level:
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"